import InfoBar from "../../components/InfoBar"
import { useStudio } from "../../contexts/StudioContext"
import TextureMapperSidebar from "./components/TextureMapperSidebar"
import TextureMapperTools from "./components/TextureMapperTools"

const TextureMapper = () => { 
    const { getSelectedProject } = useStudio()
    const project = getSelectedProject()

    return (
        <div className="h-full grid grid-areas-texture"
            key={project.identifier}
            style={{
                //These would be generated by moving the panels around.
                //For now, we just hardcode them
                gridTemplateColumns: '32px auto 300px',
                gridTemplateRows: 'auto 0 28px'
            }}
        >
            <div className="grid-in-layers border dark:border-black border-white"><TextureMapperSidebar /></div>
            <div className="grid-in-tools border dark:border-black border-white"><TextureMapperTools /></div>
            <div className="grid-in-canvas border dark:border-black border-white bg-gray-700">Put map here</div>
            <div className="grid-in-info border dark:border-black border-white"><InfoBar /></div>
        </div>
    )
}

export default TextureMapper;