name: Bug Report
about: Create a bug report to help us improve
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes: 
      value: | 
        Thanks for taking the time to help us by filling out this bug report!
  - type: markdown
    attributes: 
      value: | 
        Before describing your issue please help us by describing where this issue happened in the following sections
  - type: dropdown
    id: version
    attributes:
      label: What version of the Studio are you using?
      options:
        - Beta (dev.dumbcode.net)
        - Release (studio.dumbcode.net)
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: Which browsers have you used to test?
      description: You may select more than one. Note, these are the main browsers we test for, other browsers may get less supprt.
      options:
        - label: Microsoft Edge
        - label: Google Chrome
        - label: Firefox
        - label: Safari for macOS
        - label: Safari for iOS
        - label: Other
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
    validations:
      required: true
  - type: markdown
    attributes: 
      value: | 
        Now lets get to the part where you can actually tell us what's wrong.
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step. Please include only steps in this section and describe behavior in later steps."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Describe what you Expect to happen
      description: "What would you expect to happen when doing the steps you provided."
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Describe your Bug
      description: "What happens instead of what you would expect. Be clear and consice. Include images/gifs if possible to help illustrate."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Give us any additional information
      description: "If there is anything else you can provide to help us get to the bottom of this please add it here. Ex: you checked the codebase and found a possible culprit, you could like those lines here."
