import InfoBar from "../../components/InfoBar"
import TexturerLayers from "./components/TexturerLayers"
import TexturerTools from "./components/TexturerTools"
import TexturerProperties from "./components/TexturerProperties"
import { TexturerViewport } from "./components/TexturerViewport"

const Texturer = () => {
    return (
        <div className="h-full grid grid-areas-texture"
            style={{
                //These would be generated by moving the panels around.
                //For now, we just hardcode them
                gridTemplateColumns: '32px auto 300px',
                gridTemplateRows: 'auto 150px 28px'
            }}
        >
            <div className="grid-in-layers border border-black"><TexturerLayers /></div>
            <div className="grid-in-tools border border-black"><TexturerTools /></div>
            <div className="grid-in-canvas border border-black"><TexturerViewport /></div>
            <div className="grid-in-properties border border-black"><TexturerProperties /></div>
            <div className="grid-in-info border border-black"><InfoBar /></div>
        </div>
    )
}



export default Texturer;