import TexturerViewBar from "./components/TexturerViewBar"
import InfoBar from "../../components/InfoBar"
import TexturerLayers from "./components/TexturerLayers"
import TexturerTools from "./components/TexturerTools"
import StudioCanvas from "../../components/StudioCanvas"
import TexturerProperties from "./components/TexturerProperties"


const Texturer = () => {
    return (
        <div className="h-full grid grid-areas-texture"
            style={{
                //These would be generated by moving the panels around.
                //For now, we just hardcode them
                gridTemplateColumns: '32px auto 100px',
                gridTemplateRows: '32px auto 150px 28px'
            }}
        >            
            <div className="grid-in-views border"><TexturerViewBar /></div>
            <div className="grid-in-layers border"><TexturerLayers /></div>
            <div className="grid-in-tools border"><TexturerTools /></div>
            <div className="grid-in-canvas border"><StudioCanvas /></div>
            <div className="grid-in-properties border"><TexturerProperties /></div>
            <div className="grid-in-info border"><InfoBar /></div>
        </div>
    )
}

export default Texturer;