import { useEffect } from "react"
import InfoBar from "../../components/InfoBar"
import { useStudio } from "../../contexts/StudioContext"
import { useObjectUnderMouse } from "../../studio/selections/ObjectClickedHook"
import TexturerProperties from "./components/TexturerProperties"
import TexturerSidebar from "./components/TexturerSidebar"
import TexturerTools from "./components/TexturerTools"
import { TexturerViewport } from "./components/TexturerViewport"

const Texturer = () => {
    const { getSelectedProject, onPostFrameListeners } = useStudio()
    const project = getSelectedProject()

    useObjectUnderMouse()

    useEffect(() => {
        const onFrame = () => {
            project.model.resetVisuals()
        }
        onPostFrameListeners.add(onFrame)
        return () => {
            onPostFrameListeners.delete(onFrame)
        }
    })
    return (
        <div className="h-full grid grid-areas-texture"
            key={project.identifier}
            style={{
                //These would be generated by moving the panels around.
                //For now, we just hardcode them
                gridTemplateColumns: '32px auto 300px',
                gridTemplateRows: 'auto 150px 28px'
            }}
        >
            <div className="grid-in-layers border dark:border-black border-white"><TexturerSidebar /></div>
            <div className="grid-in-tools border dark:border-black border-white"><TexturerTools /></div>
            <div className="grid-in-canvas border dark:border-black border-white"><TexturerViewport /></div>
            <div className="grid-in-properties border dark:border-black border-white"><TexturerProperties /></div>
            <div className="grid-in-info border dark:border-black border-white"><InfoBar /></div>
        </div>
    )
}



export default Texturer;