export const MCP_ACTIONS = [
  "ping",
  "get_state",
  "get_action_schema",
  "set_active_tab",
  "new_project",
  "list_projects",
  "select_project",
  "rename_project",
  "close_project",
  "set_model_metadata",
  "set_texture_size",
  "list_cubes",
  "select_cubes",
  "create_cube",
  "update_cube",
  "set_cube_shape",
  "paint_cube_texture",
  "delete_cube",
  "reparent_cube",
  "duplicate_cube",
  "run_model_command",
  "run_animator_command",
  "list_animations",
  "create_animation",
  "select_animation",
  "update_animation",
  "delete_animation",
  "list_keyframes",
  "create_keyframe",
  "update_keyframe",
  "delete_keyframe",
  "set_keyframe_transform",
  "list_keyframe_layers",
  "create_keyframe_layer",
  "update_keyframe_layer",
  "delete_keyframe_layer",
  "set_temporary_parent",
  "export_asset",
  "import_asset",
]

export const MCP_ACTION_DESCRIPTIONS = {
  ping: "Verify that the Studio browser bridge is online.",
  get_state: "Return complete high-level state for projects, model cubes, animations, keyframes, layers, selection, active tab, and undo/redo status.",
  get_action_schema: "Return the REST/MCP action catalog and argument contract.",
  set_active_tab: "Switch the visible Studio tab by name: Project, Modeler, Mapper, Texturer, Animator, Showcase, or Options.",
  new_project: "Create and select a new DumbCode Studio project.",
  list_projects: "List open projects.",
  select_project: "Select an open project by projectId, identifier, name, or index.",
  rename_project: "Rename a project.",
  close_project: "Close a project.",
  set_model_metadata: "Merge metadata into the selected model.",
  set_texture_size: "Set model texture width and height.",
  list_cubes: "List cubes in the selected project, including hierarchy and transform data.",
  select_cubes: "Select cubes by id, identifier, name, or path.",
  create_cube: "Create a cube under the model root, as a sibling of a target cube, or as a child of a target cube.",
  update_cube: "Update cube name, dimensions, rotation point, offset, rotation, cube grow, texture offset/mirroring, visibility, lock state, metadata, or parent.",
  set_cube_shape: "Update cube dimensions and/or cube grow in one batch (visual shape / hitbox in the modeler).",
  paint_cube_texture: "Fill solid RGB(A) color onto this cube's UV rectangles on a raster texture (same atlas layout as the texture mapper preview).",
  delete_cube: "Delete cubes, optionally keeping their children by moving those children up to the deleted cube's parent.",
  reparent_cube: "Move a cube under another cube or back to the root.",
  duplicate_cube: "Clone a cube subtree and add it under a requested parent/root.",
  run_model_command: "Run an existing DumbCode Studio model command string.",
  run_animator_command: "Run an existing DumbCode Studio animator command string.",
  list_animations: "List animations on the selected project.",
  create_animation: "Create and select an animation.",
  select_animation: "Select an animation by id, identifier, name, or index.",
  update_animation: "Update animation name, skeleton/name override flags, current time, playback flag, IK anchor cubes, IK direction, and loop data.",
  delete_animation: "Delete an animation from the selected project.",
  list_keyframes: "List keyframes on the selected or specified animation.",
  create_keyframe: "Create a keyframe with start time, duration, layer, selection flag, progression points, and optional transform maps.",
  update_keyframe: "Update keyframe timing, selection, layer, progression points, and transform maps.",
  delete_keyframe: "Delete a keyframe.",
  set_keyframe_transform: "Set or clear one cube's position, rotation, and cube-grow deltas on a keyframe.",
  list_keyframe_layers: "List keyframe layers on an animation.",
  create_keyframe_layer: "Create a keyframe layer and set its properties.",
  update_keyframe_layer: "Update keyframe layer name, visibility, lock state, and defined mode.",
  delete_keyframe_layer: "Delete a keyframe layer and keyframes on that layer.",
  set_temporary_parent: "Set or remove animator temporary parenting between cubes.",
  export_asset: "Export selected project/model/animation as base64 .dcproj, .dcm, or .dca data.",
  import_asset: "Import a base64 .dcproj, .bbmodel, .dcm, .tbl, or .dca asset. Animations import into the selected project.",
}

export const MCP_ACTION_SCHEMA = {
  ping: {},
  get_state: { includeHistory: "boolean optional; include undo/redo summaries", includeCommands: "boolean optional; include command names" },
  get_action_schema: {},
  set_active_tab: { tab: "Project | Modeler | Mapper | Texturer | Animator | Showcase | Options" },
  new_project: { name: "string optional" },
  list_projects: {},
  select_project: { projectId: "project identifier/name/index; optional means selected/current" },
  rename_project: { projectId: "optional project selector", name: "new project name" },
  close_project: { projectId: "optional project selector" },
  set_model_metadata: { projectId: "optional project selector", metadata: "object of string values" },
  set_texture_size: { projectId: "optional project selector", width: "number", height: "number" },
  list_cubes: { projectId: "optional project selector", includeChildren: "boolean optional" },
  select_cubes: { projectId: "optional project selector", cubes: "array of cube ids/names/paths", mode: "replace | add | remove; default replace" },
  create_cube: { projectId: "optional project selector", name: "string optional", parent: "cube selector optional", siblingOf: "cube selector optional", dimension: "[x,y,z] optional", position: "[x,y,z] optional", offset: "[x,y,z] optional", rotation: "[x,y,z] optional", cubeGrow: "[x,y,z] optional", textureOffset: "[u,v] optional", textureMirrored: "boolean optional", hideChildren: "boolean optional", visible: "boolean optional", locked: "boolean optional", metadata: "object optional" },
  update_cube: { projectId: "optional project selector", cube: "cube selector", name: "string optional", dimension: "[x,y,z] optional", position: "[x,y,z] optional", offset: "[x,y,z] optional", rotation: "[x,y,z] optional", cubeGrow: "[x,y,z] optional", textureOffset: "[u,v] optional", textureMirrored: "boolean optional", visible: "boolean optional", locked: "boolean optional", hideChildren: "boolean optional", metadata: "object optional", parent: "cube selector/null optional" },
  set_cube_shape: { projectId: "optional project selector", cube: "cube selector", dimension: "[x,y,z] optional", cubeGrow: "[x,y,z] optional" },
  paint_cube_texture: { projectId: "optional project selector", cube: "cube selector", color: "[r,g,b] or [r,g,b,a] integers 0-255", faces: "all | one face string | array; indices 0-5 = +X,-X,+Y,-Y,+Z,-Z (east,west,up,down,south,north). Many aliases: px/nx/py/ny/pz/nz, right/left/top/bottom/front/back, uv_east...uv_north, face0...face5, pos_x, forward, ...", textureId: "optional texture identifier to paint on; default first texture in selected group or default group" },
  delete_cube: { projectId: "optional project selector", cube: "single cube selector optional if cubes is omitted", cubes: "array of cube selectors optional", keepChildren: "boolean optional" },
  reparent_cube: { projectId: "optional project selector", cube: "cube selector", parent: "cube selector or null for root" },
  duplicate_cube: { projectId: "optional project selector", cube: "cube selector", parent: "cube selector optional/null", name: "string optional" },
  run_model_command: { projectId: "optional project selector", command: "existing modeler command text" },
  run_animator_command: { projectId: "optional project selector", command: "existing animator command text" },
  list_animations: { projectId: "optional project selector" },
  create_animation: { projectId: "optional project selector", name: "string optional", select: "boolean optional", isSkeleton: "boolean optional" },
  select_animation: { projectId: "optional project selector", animation: "animation selector" },
  update_animation: { projectId: "optional project selector", animation: "animation selector optional", name: "string optional", isSkeleton: "boolean optional", nameOverridesOnly: "boolean optional", time: "number optional", playing: "boolean optional", ikAnchorCubes: "array cube selectors optional", ikDirection: "upwards | downwards optional", loopData: "{exists,start,end,duration} optional" },
  delete_animation: { projectId: "optional project selector", animation: "animation selector" },
  list_keyframes: { projectId: "optional project selector", animation: "animation selector optional" },
  create_keyframe: { projectId: "optional project selector", animation: "animation selector optional", layerId: "number optional", startTime: "number optional", duration: "number optional", selected: "boolean optional", progressionPoints: "[{x,y,required?}] optional", position: "record cubeName->[x,y,z] optional", rotation: "record cubeName->[x,y,z] optional", cubeGrow: "record cubeName->[x,y,z] optional" },
  update_keyframe: { projectId: "optional project selector", animation: "animation selector optional", keyframe: "keyframe selector", layerId: "number optional", startTime: "number optional", duration: "number optional", selected: "boolean optional", progressionPoints: "array optional", position: "record optional; null values clear entries", rotation: "record optional; null values clear entries", cubeGrow: "record optional; null values clear entries" },
  delete_keyframe: { projectId: "optional project selector", animation: "animation selector optional", keyframe: "keyframe selector" },
  set_keyframe_transform: { projectId: "optional project selector", animation: "animation selector optional", keyframe: "keyframe selector", cube: "cube selector/name", position: "[x,y,z] or null optional", rotation: "[x,y,z] or null optional", cubeGrow: "[x,y,z] or null optional", useCubeName: "boolean optional; default true" },
  list_keyframe_layers: { projectId: "optional project selector", animation: "animation selector optional" },
  create_keyframe_layer: { projectId: "optional project selector", animation: "animation selector optional", layerId: "number optional", name: "string optional", visible: "boolean optional", locked: "boolean optional", definedMode: "boolean optional" },
  update_keyframe_layer: { projectId: "optional project selector", animation: "animation selector optional", layerId: "number", name: "string optional", visible: "boolean optional", locked: "boolean optional", definedMode: "boolean optional" },
  delete_keyframe_layer: { projectId: "optional project selector", animation: "animation selector optional", layerId: "number" },
  set_temporary_parent: { projectId: "optional project selector", animation: "animation selector optional", cube: "cube selector", parent: "cube selector or null" },
  export_asset: { projectId: "optional project selector", format: "dcproj | dcm | dca", animation: "animation selector required for dca unless selected animation exists" },
  import_asset: { filename: "string", base64: "base64 file contents", mimeType: "string optional", projectId: "optional project selector for .dca imports", select: "boolean optional" },
}
