export declare const MCP_ACTIONS: readonly [
  "ping",
  "get_state",
  "get_action_schema",
  "set_active_tab",
  "new_project",
  "list_projects",
  "select_project",
  "rename_project",
  "close_project",
  "set_model_metadata",
  "set_texture_size",
  "list_cubes",
  "select_cubes",
  "create_cube",
  "update_cube",
  "set_cube_shape",
  "paint_cube_texture",
  "delete_cube",
  "reparent_cube",
  "duplicate_cube",
  "run_model_command",
  "run_animator_command",
  "list_animations",
  "create_animation",
  "select_animation",
  "update_animation",
  "delete_animation",
  "list_keyframes",
  "create_keyframe",
  "update_keyframe",
  "delete_keyframe",
  "set_keyframe_transform",
  "list_keyframe_layers",
  "create_keyframe_layer",
  "update_keyframe_layer",
  "delete_keyframe_layer",
  "set_temporary_parent",
  "export_asset",
  "import_asset"
]
export type McpActionName = typeof MCP_ACTIONS[number]
export declare const MCP_ACTION_DESCRIPTIONS: Record<McpActionName, string>
export declare const MCP_ACTION_SCHEMA: Record<McpActionName, Record<string, string>>
