import { useEffect } from "react"
import InfoBar from "../../components/InfoBar"
import StudioCanvas from "../../components/StudioCanvas"
import { useStudio } from "../../contexts/StudioContext"
import { useListenableObject } from "../../studio/util/ListenableObject"
import { useObjectUnderMouse } from "../../studio/util/ObjectClickedHook"
import AnimatorGumballPropertiesBar from "../animator/components/AnimatorGumballPropertiesBar"
import ShowcaseSidebar from "./components/ShowcaseSidebar"
import { useShowcaseGumball } from "./logic/ShowcaseGumball"

const Showcase = () => {
  const { scene, lightGroup, itemsGroup, getSelectedProject, onFrameListeners, renderer } = useStudio()
  const project = getSelectedProject()
  const [view] = useListenableObject(project.showcaseProperties.selectedView)

  useObjectUnderMouse()
  useShowcaseGumball()

  useEffect(() => {
    scene.remove(lightGroup)
    scene.remove(itemsGroup)
    scene.add(project.showcaseProperties.group)
    renderer.shadowMap.enabled = true
    const onFrame = () => {
      view.renderForGumball()
    }
    onFrameListeners.add(onFrame)

    return () => {
      scene.add(lightGroup)
      scene.add(itemsGroup)
      scene.remove(project.showcaseProperties.group)
      renderer.shadowMap.enabled = false

      onFrameListeners.delete(onFrame)
    }
  }, [view, scene, lightGroup, itemsGroup, project, renderer, onFrameListeners])
  return (
    <div className="h-full grid grid-areas-showcase"
      key={project.identifier}
      style={{
        //These would be generated by moving the panels around.
        //For now, we just hardcode them
        gridTemplateColumns: 'auto 300px',
        gridTemplateRows: 'auto 30px 28px'
      }}
    >
      <div className="grid-in-canvas border dark:border-black border-white min-h-0"><StudioCanvas /></div>
      <div className="grid-in-info border dark:border-black border-white"><InfoBar /></div>
      <div className="grid-in-gumball border dark:border-black border-white"><AnimatorGumballPropertiesBar consumer={view} /></div>
      <div className="grid-in-sidebar border dark:border-black border-white"><ShowcaseSidebar /></div>
    </div>
  )
}



export default Showcase;