name: Publish Dev Website
on:
  push:
    branches: [ react ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: dev.dumbcode.net
        username: ubuntu
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: ./var/www/dumbcode.net/dev/